spring.application.name=patient-service
#Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/patientdb
spring.datasource.username=postgres
spring.datasource.password=SpringBoot@2026
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
#Port configuration
server.port=8080
#Path configuration
server.servlet.context-path=/app/
# SWAGGER
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
#Turn off Spring banner
spring.main.banner-mode=off
#Reduce logging level, St logging level to warn
logging.level.root=warn