spring.application.name=patient-service
# Database Configuration (with default fallbacks)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/patientdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:SpringBoot@2026}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
# Profile Configuration
spring.profiles.active=dev
# Port configuration
server.port=8080
# Path configuration
server.servlet.context-path=/app/
# SWAGGER
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
# Turn off Spring banner
spring.main.banner-mode=off
# Reduce logging level
logging.level.root=warn
# SECURITY (with default fallbacks)
spring.security.user.name=${SPRING_SECURITY_USER_NAME:admin}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD:password}
# ACTUATOR CONFIGURATION
springdoc.show-actuator=true
info.app.name=Patient Service
info.app.description=Patient Management Microservice
info.app.version=1.0.0
info.developer.name=Gboluwaga
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.db.enabled=true