db-active.ip=127.0.0.1
db-active.password=password
# DB Configuration
# Mongo DB Configuration
mongodb-active.ip=10.9.44.563
# Redis Configuration
redis-active.ip=10.9.44.564
redis-active.password=dev_redis_pass
# Kafka Configuration
kafka-active.url=10.9.44.565:9092word